package com.chugalkhorbandar.application.context.knowledge;

public enum KnowledgeFragmentType {
    IDENTITY,
    PERSONALITY,
    SPEAKING_STYLE,
    STORYTELLING,
    HUMOR,
    SECRET_POLICY,
    CHARACTER_OPINION,
    RELATIONSHIP_TO_BANDAR,
    WORLD_GEOGRAPHY,
    WORLD_HISTORY,
    WORLD_POLITICS,
    WORLD_SPECIES,
    WORLD_ECONOMY,
    WORLD_TRANSPORT,
    CHARACTER_PROFILE,
    CHARACTER_LOCATION,
    CHARACTER_TITLES,
    CHARACTER_RELATIONSHIPS,
    CHARACTER_PREFERENCES,
    STORY_SUMMARY,
    TIMELINE,
    CONVERSATION,
    WORKING_MEMORY,
    UNKNOWN
}
