package com.chugalkhorbandar.application.prompt;

public enum PromptSectionType {
    CURRENT_USER,
    PERSONALITY,
    RELATIONSHIP_TO_BANDAR,
    WORLD_FACTS,
    CURRENT_CHARACTER,
    CURRENT_LOCATION,
    RELATIONSHIPS,
    RELEVANT_STORIES,
    CURRENT_CONVERSATION,
    WORKING_MEMORY,
    SESSION_SUMMARY,
    PUBLIC_EVENTS,
    LONG_TERM_MEMORY,
    SECRET_MEMORY,
    INSTRUCTIONS,
    CONVERSATION_STYLE,
    USER_MESSAGE,
    UNKNOWN
}
